import { z } from "zod"

export const eventTypes = [
  "mission.created",
  "mission.submitted",
  "mission.analysis.started",
  "mission.analysis.updated",
  "mission.plan.proposed",
  "mission.plan.accepted",
  "mission.plan.regenerating",
  "mission.plan.denied",
  "mission.team.assembly.started",
  "mission.team.member.selected",
  "mission.team.assembly.completed",
  "mission.started",
  "mission.paused",
  "mission.resumed",
  "mission.blocked",
  "mission.completed",
  "mission.failed",
  "mission.cancelled",
  "model.connection.changed",
  "model.request.started",
  "model.request.completed",
  "model.request.failed",
  "staff.assigned",
  "staff.status.changed",
  "staff.action.started",
  "staff.action.updated",
  "staff.action.completed",
  "staff.file.opened",
  "staff.file.read",
  "staff.file.created",
  "staff.file.updated",
  "staff.file.saved",
  "staff.file.deleted",
  "staff.command.started",
  "staff.command.output",
  "staff.command.completed",
  "staff.research.started",
  "staff.research.result",
  "staff.decision.recorded",
  "staff.test.started",
  "staff.test.result",
  "handoff.preparing",
  "handoff.started",
  "handoff.accepted",
  "handoff.completed",
  "approval.requested",
  "approval.accepted",
  "approval.rejected",
  "artifact.created",
  "artifact.updated",
  "activity.created",
] as const

export const eventPayloadSchema = z.object({
  title: z.string().optional(),
  summary: z.string().optional(),
  objective: z.string().optional(),
  status: z.string().optional(),
  severity: z.string().optional(),
  tool: z.string().optional(),
  url: z.string().optional(),
  verdict: z.string().optional(),
  screenshot_path: z.string().optional(),
  error: z.string().optional(),
  file_path: z.string().optional(),
  progress_percent: z.number().min(0).max(100).optional(),
  phase: z.string().optional(),
  handoff_id: z.string().optional(),
  from_staff_id: z.string().optional(),
  to_staff_id: z.string().optional(),
  artifact_id: z.string().optional(),
  artifact_type: z.string().optional(),
  artifact_count: z.number().int().nonnegative().optional(),
  tool_name: z.string().optional(),
  command: z.string().optional(),
  next_action: z.string().optional(),
  team_id: z.string().optional(),
  notes: z.string().optional(),
  roles: z.array(z.string()).optional(),
  changed_paths: z.array(z.string()).optional(),
  test_instructions: z.array(z.string()).optional(),
  acceptance_criteria: z.array(z.string()).optional(),
  artifact_ids: z.array(z.string()).optional(),
}).passthrough()

export const eventEnvelopeSchema = z.object({
  version: z.literal("1.0"),
  event_id: z.string(),
  event_type: z.enum(eventTypes),
  timestamp: z.string(),
  project_id: z.string(),
  mission_id: z.string(),
  staff_id: z.string().nullable(),
  sequence: z.number().int().positive(),
  payload: eventPayloadSchema,
})

export type EventEnvelope = z.infer<typeof eventEnvelopeSchema>
